### ISSUE TITLE
Incorrect usage? Running checkrebuild returns "error: no targets specified (use -h for help)"

### ISSUE THREAD

**Issue by tdnicholson** [maximbaz/rebuild-detector#15]
I first just ran "checkrebuild" as indicated in the readme.md, but nothing happens. Then I ran "checkrebuild -v" and I get the error:

error: no targets specified (use -h for help)

I tried "checkrebuild -h" to see what that said, and I get the error:

/usr/bin/checkrebuild: illegal option -- h

Then I thought, maybe I have to run it with SUDO privileges, so I tried that, same result.

I must not be using this correctly, but I can't figure out what I'm doing wrong. Please help.

Thanks.

**Comment by max-baz** [comment]
Hi, thanks for the report! You are using it correctly, `checkrebuild` without any arguments doesn't print anything simply because there is nothing to rebuild, everything is good 🙂 

It's a mistake on my side that `-v` prints that error, I'll look into it. 

I'll also add a note to the README that an empty output with exit code 0 is expected and means that everything is up-to-date.

**Comment by max-baz** [comment]
Fixed in 4.1.6, please confirm that you get no error messages anymore with or without `-v` 🙂
