### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by df8oe** [maximbaz/rebuild-detector#24]
There are many aur packages which provide binaries. Detection of such packages should be suppressable via a whitelist which the user can create / edit. This would improve the readability of the output to only show the packages where the issues can be removed by a new build.

**Comment by max-baz** [comment]
Hello, it's already possible, what you want to achieve is trivially scripted using `| grep -v pkgname`, as described in the last paragraph or https://github.com/maximbaz/rebuild-detector#what-do-i-do-if-a-package-is-flagged.

**Comment by df8oe** [comment]
On my system the list has grown up to 27 packages. This soultion is not handy enough to solve the isue.

**Comment by max-baz** [comment]
grep is also able to read patterns from a file, if you prefer to maintain the list separately, instead of together with the filtering logic?

**Comment by df8oe** [comment]
yes of course. I can write a bash script (1 line...) which simply calls checkrebuild piping it through grep. Do you not think it is much more elegant to let checkrebuild read the list autonomous? What arguments are against this?

**Comment by max-baz** [comment]
It's intentionally made to be suitable for composition, some would want to maintain a whitelist, others blacklist, others exclude only a specific version, others exclude until next major version, others want to exclude all `-bin` packages, etc... instead of supporting all this and other variety, the script focuses on doing one thing well, and present the output in such a way that is easy to filter how ever you want 🙂

**Comment by df8oe** [comment]
Thank you for discussing this. I will think of publishing a wrapper what will do this or find another solution.
