### ISSUE TITLE
Warning: $HOME not set. Using /tmp.

### ISSUE THREAD

**Issue by jrd** [maximbaz/rebuild-detector#35]
I regulary have this in my pamac `checkrebuild` output:

```
...
Checking which packages need to be rebuilt
parallel: Warning: $HOME not set. Using /tmp.
Updating the desktop file MIME type cache...
...
```

You can reproduce the error easily:
```sh
$ env HOME= checkrebuild
```

As there is already a temporary folder named `$log` it’s easy to correct this:

In `get_broken_ldd_pkgs` around line 77:
```sh
filter_executable |
env HOME="$log" parallel --will-cite 'check_broken_ldd "{}"'
```

I can provide a pull request if necessary but it’s really easy to fix.

**Comment by max-baz** [comment]
Thanks for the report! Makes sense to silence this warning, what do you think about https://github.com/maximbaz/rebuild-detector/commit/bcd1faeb24ca2f059e3d97b15fc40b81844860b3 ? I just went with setting it to `/tmp` as (1) it's what `parallel` itself apparently wants to fallback to, and (2) since `parallel` actually does create new folders and files in that folder, it might be easier to not mix that up with a folder that we actually use.

**Comment by jrd** [comment]
Seems good to me ;-)
You can close this issue.
Thank you
